export default {
  COLORS: {
    BACKGROUND: '#000000',  // PRETO 

    PRIMARY_900: '#5A7F78',  // VERDE
    PRIMARY_600: '#314C53', // VERDE ESCURO
    

    TEXT_SECONDARY: '#FBB043',  // AMARELO
    TEXT_PRIMARY: '#FFFFFF',  // BRANCO
  }
}