export default {
  COLORS: {
    BACKGROUND: '#F7F8FC',  // BRANCO GELADA

    PRIMARY_900: '#010300',  // PRETO
    PRIMARY_600: '#BBDEC6',  // VERDE CLARO

    TEXT_SECONDARY: '#314C53', // VERDE ESCURO
    TEXT_PRIMARY: '#5A7F78',  // VERDE
  }
}